---
- name: are we configuring kerberos?
  set_fact:
    aaa_sso_krb5: true
    aaa_pkgs: "{{ aaa_pkgs | union(aaa_pkgs_krb5) }}"
  when: aaa_sso_keytab is defined or aaa_sso_remote_keytab is defined

- name: assert we don't have aaa_sso_keytab and aaa_sso_remote_keytab together
  assert:
    that: aaa_sso_remote_keytab is not defined
    msg: >
      Variables aaa_sso_keytab and aaa_sso_remote_keytab are mutually exclusive
  when: aaa_sso_keytab is defined

- name: set up remote keytab path
  set_fact:
    aaa_sso_keytab_path: "{{ aaa_sso_remote_keytab }}"
  when: aaa_sso_remote_keytab is defined

- name: Install AAA packages
  package:
    name: "{{ aaa_pkgs }}"
    state: present

- name: Deploy profile
  template:
    src: profile
    dest: /etc/ovirt-engine/aaa/{{ aaa_profile_name }}.properties
    owner: ovirt
    mode: 0600
  notify:
    - restart ovirt-engine

- name: Deploy normal ldap authn
  template:
    src: authn
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-authn.properties
  notify:
    - restart ovirt-engine
  when: not aaa_sso_krb5

- name: Deploy http authn
  template:
    src: httpauthn
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-http-authn.properties
  notify:
    - restart ovirt-engine
  when: aaa_sso_krb5

- name: Deploy http mapping
  template:
    src: mapping
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-http-mapping.properties
  notify:
    - restart ovirt-engine
  when: aaa_sso_krb5

- name: Deploy authz
  template:
    src: authz
    dest: /etc/ovirt-engine/extensions.d/{{ aaa_profile_name }}-authz.properties
  notify:
    - restart ovirt-engine

- name: Deploy JAAS
  template:
    src: jaas
    dest: /etc/ovirt-engine/engine.conf.d/99-jaas.conf
  notify:
    - restart ovirt-engine
  when: (ovirt_jaas_ticket_cache_path is defined or
          ovirt_jaas_keytab_path is defined)

- name: Copy keytab
  copy:
    src: "{{ aaa_sso_keytab }}"
    dest: "{{ aaa_sso_keytab_path }}"
    owner: apache
    mode: 0600
  when: aaa_sso_keytab is defined
  notify:
    - restart httpd

- name: Deploy kerberos SSO
  template:
    src: sso
    dest: /etc/ovirt-engine/aaa/ovirt-sso.conf
  when: aaa_sso_krb5
  notify:
    - restart httpd

- name: Create symlink to apache configuration
  file:
    src: /etc/ovirt-engine/aaa/ovirt-sso.conf
    dest: /etc/httpd/conf.d/ovirt-sso.conf
    state: link
  when: aaa_sso_krb5 is defined
  notify:
    - restart httpd

- name: Test AAA profile
  command: >
    /usr/bin/ovirt-engine-extensions-tool
    --extension-file=/etc/ovirt-engine/extensions.d/{{
    aaa_profile_name | quote }}-authn.properties
    --extension-file=/etc/ovirt-engine/extensions.d/{{
    aaa_profile_name | quote }}-authz.properties aaa search
    --extension-name={{ aaa_profile_name | quote }}-authz
  changed_when: false
